server:
  port: 8001
  
spring:
  application:
    name: proxy
  cloud:
    gateway:
      routes:
      - id: auth      
        uri: lb://auth
#        uri: http://localhost:1234
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
        
