server:
  port: 8001

eureka:
  instance:
    hostname: eureka
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - "*"      
  
spring:
  application:
    name: proxy
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
      - id: auth      
        uri: lb://auth
#        uri: http://localhost:1234
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
        
